/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.sergiopt.formulario;

import es.sergiopt.map.Ejercicio;
import es.sergiopt.map.EjercicioMusculo;
import es.sergiopt.map.Musculo;
import es.sergiopt.services.EjercicioMusculoService;
import es.sergiopt.services.EjercicioService;
import es.sergiopt.services.MusculoService;
import java.awt.event.ItemEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import es.sergiopt.utils.AyudaUtil;

/**
 *
 * @author sergiopt
 */
public class Formulario extends javax.swing.JFrame {       
    
    private AyudaUtil ayudaUtil;
    private DefaultTableModel tableModel;    
    
    private Boolean cargarDatos;
    private Boolean validarImagen;
    private Boolean esEjercicioSeleccionado;
    
    private List<EjercicioMusculo> musculosInvolucrados;
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        // Inicializaciones
        cargarDatos = false;
        validarImagen = false;
        esEjercicioSeleccionado = false;
        musculosInvolucrados = new ArrayList<>();
        
        // Componentes
        initComponents();
        
        tableModel = new DefaultTableModel();
        tableModel = (DefaultTableModel) tblEjercicios.getModel();
        
        // Cargar músculos en combo box
        List<Musculo> musculos = MusculoService.getAll();       
        for (Musculo musculo : musculos) cbMusculos.addItem(musculo);                        
        
        ayudaUtil = new AyudaUtil();

        // Cargar ejercicios en tabla
        List<Ejercicio> ejercicios = EjercicioService.getAll();
        for (Ejercicio ejercicio : ejercicios) {
            Object[] row = {ejercicio.getId(), ejercicio.getNombre(), ejercicio.getRutaImagen(), ejercicio.getPesoMinimo(), ejercicio.getPesoMaximo()};
            tableModel.addRow(row);
        }
    }
    
    private void reiniciarCampos() {
        txtNombreEjercicio.setText("");
        txtDescripcionEjercicio.setText("");
        txtImagen.setText("");
        txtPesoMinimo.setText("");
        txtPesoMaximo.setText("");
        txtDescripcionEjMusculo.setText("");
        txtActivacionEjMusculo.setText("");
        btnNoDirectoEjMusculo.setSelected(true);
        txtaDetallesEjercicio.setText("");
        validarImagen = false;
        
        modificarVistaComponentesMusculo(false);
        musculosInvolucrados = new ArrayList<>();
    }
    
    private void recargarEjercicios() {
        tableModel.setRowCount(1); // sigue conteniendo vacía
        List<Ejercicio> ejercicios = EjercicioService.getAll();
        for (Ejercicio ejercicio : ejercicios) {
            Object[] row = {ejercicio.getId(), ejercicio.getNombre(), ejercicio.getRutaImagen()};
            tableModel.addRow(row);
        }
    }
    
    private void modificarVistaComponentesMusculo(boolean esHabilitado) {
        txtDescripcionEjMusculo.setEnabled(esHabilitado);
        txtActivacionEjMusculo.setEnabled(esHabilitado);
        btnNoDirectoEjMusculo.setEnabled(esHabilitado);
        btnSiEsDirectoEjMusculo.setEnabled(esHabilitado);
        btnGuardarEjMusculo.setEnabled(esHabilitado);
        btnEliminarEjMusculo.setEnabled(esHabilitado);
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngEsInvolucrado = new javax.swing.ButtonGroup();
        btngEsDirecto = new javax.swing.ButtonGroup();
        pnlFormulario = new javax.swing.JPanel();
        lblEjercicio = new javax.swing.JLabel();
        pnlEjercicio = new javax.swing.JPanel();
        lblNombreEjercicio = new javax.swing.JLabel();
        txtNombreEjercicio = new javax.swing.JTextField();
        lbDescripcionEjercicio = new javax.swing.JLabel();
        txtDescripcionEjercicio = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        btnValidarImagen = new javax.swing.JToggleButton();
        lblPesoMinimo = new javax.swing.JLabel();
        txtPesoMinimo = new javax.swing.JTextField();
        lblPesoMaximo = new javax.swing.JLabel();
        txtPesoMaximo = new javax.swing.JTextField();
        lblMusculos = new javax.swing.JLabel();
        pnlMusculos = new javax.swing.JPanel();
        lblCbMusculos = new javax.swing.JLabel();
        cbMusculos = new javax.swing.JComboBox<>();
        lblEsInvolucrado = new javax.swing.JLabel();
        btnNoEsInvolucrado = new javax.swing.JRadioButton();
        btnSiEsInvolucrado = new javax.swing.JRadioButton();
        lblDescripcionEjMusculo = new javax.swing.JLabel();
        txtDescripcionEjMusculo = new javax.swing.JTextField();
        lblActivacionEjMusculo = new javax.swing.JLabel();
        txtActivacionEjMusculo = new javax.swing.JTextField();
        lblEsDirectoEjMusculo = new javax.swing.JLabel();
        btnNoDirectoEjMusculo = new javax.swing.JRadioButton();
        btnSiEsDirectoEjMusculo = new javax.swing.JRadioButton();
        btnGuardarEjMusculo = new javax.swing.JButton();
        btnEliminarEjMusculo = new javax.swing.JButton();
        btnGuardarEjercicioMusculos = new javax.swing.JButton();
        lblEjerciciosCargados = new javax.swing.JLabel();
        spEjercicios = new javax.swing.JScrollPane();
        tblEjercicios = new javax.swing.JTable();
        btnEliminarEjercicio = new javax.swing.JButton();
        lblDetallesEjercicio = new javax.swing.JLabel();
        spDetallesEjercicio = new javax.swing.JScrollPane();
        txtaDetallesEjercicio = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        menuAyuda = new javax.swing.JMenu();
        mitemSobre = new javax.swing.JMenuItem();
        mitemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración Ejercicios Gym");
        setMinimumSize(new java.awt.Dimension(1280, 720));

        lblEjercicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEjercicio.setText("Ejercicio");

        pnlEjercicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreEjercicio.setText("Nombre");

        lbDescripcionEjercicio.setText("Descripción");

        lblImagen.setText("Imagen");

        btnValidarImagen.setText("Validar");
        btnValidarImagen.addActionListener(this::btnValidarImagenActionPerformed);

        lblPesoMinimo.setText("Peso minimo");

        lblPesoMaximo.setText("Peso máximo");

        javax.swing.GroupLayout pnlEjercicioLayout = new javax.swing.GroupLayout(pnlEjercicio);
        pnlEjercicio.setLayout(pnlEjercicioLayout);
        pnlEjercicioLayout.setHorizontalGroup(
            pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjercicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEjercicioLayout.createSequentialGroup()
                        .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEjercicioLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEjercicioLayout.createSequentialGroup()
                                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbDescripcionEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreEjercicio)
                            .addComponent(txtDescripcionEjercicio)
                            .addGroup(pnlEjercicioLayout.createSequentialGroup()
                                .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnValidarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                    .addGroup(pnlEjercicioLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblPesoMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesoMinimo)
                        .addGap(33, 33, 33)
                        .addComponent(lblPesoMaximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesoMaximo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEjercicioLayout.setVerticalGroup(
            pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjercicioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEjercicio)
                    .addComponent(lblNombreEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionEjercicio)
                    .addComponent(lbDescripcionEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImagen)
                    .addComponent(btnValidarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesoMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesoMinimo)
                    .addComponent(lblPesoMaximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesoMaximo))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lblMusculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMusculos.setText("Músculos involucrados");

        pnlMusculos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCbMusculos.setText("Músculo");

        cbMusculos.addItemListener(this::cbMusculosItemStateChanged);
        cbMusculos.addActionListener(this::cbMusculosActionPerformed);

        lblEsInvolucrado.setText("Es involucrado");

        btngEsInvolucrado.add(btnNoEsInvolucrado);
        btnNoEsInvolucrado.setSelected(true);
        btnNoEsInvolucrado.setText("No");
        btnNoEsInvolucrado.addActionListener(this::btnNoEsInvolucradoActionPerformed);

        btngEsInvolucrado.add(btnSiEsInvolucrado);
        btnSiEsInvolucrado.setText("Si");
        btnSiEsInvolucrado.addActionListener(this::btnSiEsInvolucradoActionPerformed);

        lblDescripcionEjMusculo.setText("Descipción");

        txtDescripcionEjMusculo.setEnabled(false);

        lblActivacionEjMusculo.setText("Porcentaje activación (0-100)");

        txtActivacionEjMusculo.setEnabled(false);

        lblEsDirectoEjMusculo.setText("Es directo");

        btngEsDirecto.add(btnNoDirectoEjMusculo);
        btnNoDirectoEjMusculo.setSelected(true);
        btnNoDirectoEjMusculo.setText("No");
        btnNoDirectoEjMusculo.setEnabled(false);

        btngEsDirecto.add(btnSiEsDirectoEjMusculo);
        btnSiEsDirectoEjMusculo.setText("Si");
        btnSiEsDirectoEjMusculo.setEnabled(false);

        btnGuardarEjMusculo.setText("Guardar músculo");
        btnGuardarEjMusculo.setEnabled(false);
        btnGuardarEjMusculo.addActionListener(this::btnGuardarEjMusculoActionPerformed);

        btnEliminarEjMusculo.setText("Eliminar músculo");
        btnEliminarEjMusculo.setEnabled(false);
        btnEliminarEjMusculo.addActionListener(this::btnEliminarEjMusculoActionPerformed);

        javax.swing.GroupLayout pnlMusculosLayout = new javax.swing.GroupLayout(pnlMusculos);
        pnlMusculos.setLayout(pnlMusculosLayout);
        pnlMusculosLayout.setHorizontalGroup(
            pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusculosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMusculosLayout.createSequentialGroup()
                        .addComponent(lblActivacionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtActivacionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(lblEsDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNoDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiEsDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addGroup(pnlMusculosLayout.createSequentialGroup()
                        .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCbMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMusculosLayout.createSequentialGroup()
                                .addComponent(cbMusculos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(58, 58, 58)
                                .addComponent(lblEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35)
                                .addComponent(btnNoEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSiEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtDescripcionEjMusculo))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMusculosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        pnlMusculosLayout.setVerticalGroup(
            pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusculosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMusculos)
                    .addComponent(lblCbMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNoEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSiEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescripcionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActivacionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtActivacionEjMusculo)
                    .addComponent(lblEsDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNoDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSiEsDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        btnGuardarEjercicioMusculos.setText("Guardar fornulario");
        btnGuardarEjercicioMusculos.addActionListener(this::btnGuardarEjercicioMusculosActionPerformed);

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(btnGuardarEjercicioMusculos, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(lblMusculos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarEjercicioMusculos)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lblEjerciciosCargados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEjerciciosCargados.setText("Ejercicios cargados");

        tblEjercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEjercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEjerciciosMouseClicked(evt);
            }
        });
        spEjercicios.setViewportView(tblEjercicios);

        btnEliminarEjercicio.setText("Eliminar ejercicio");
        btnEliminarEjercicio.addActionListener(this::btnEliminarEjercicioActionPerformed);

        lblDetallesEjercicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDetallesEjercicio.setText("Detalles del ejercicio");

        txtaDetallesEjercicio.setEditable(false);
        txtaDetallesEjercicio.setColumns(20);
        txtaDetallesEjercicio.setRows(5);
        spDetallesEjercicio.setViewportView(txtaDetallesEjercicio);

        menuAyuda.setText("Ayuda");

        mitemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitemSobre.setText("Sobre");
        mitemSobre.addActionListener(this::mitemSobreActionPerformed);
        menuAyuda.add(mitemSobre);

        mitemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitemSalir.setText("Salir");
        mitemSalir.addActionListener(this::mitemSalirActionPerformed);
        menuAyuda.add(mitemSalir);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEjerciciosCargados)
                    .addComponent(lblDetallesEjercicio)
                    .addComponent(spEjercicios, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(spDetallesEjercicio)
                    .addComponent(btnEliminarEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblEjerciciosCargados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spEjercicios, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarEjercicio)
                        .addGap(29, 29, 29)
                        .addComponent(lblDetallesEjercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spDetallesEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarImagenActionPerformed
        String rutaImagen = txtImagen.getText();
        if (rutaImagen == null || rutaImagen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Se debe especificar una ruta absoluta de la imagen (ej: /home/admin/imagenes/banca.jpg)");
            return;
        }
        
        File imagen = new File(rutaImagen);
        if (!imagen.exists() || !imagen.isFile()) {
            JOptionPane.showMessageDialog(this, "La imagen no existe");
            return;
        } 
        
        if (!(rutaImagen.endsWith(".jpg") || rutaImagen.endsWith(".jpeg"))) {
            JOptionPane.showMessageDialog(this, "El formato de la foto debe ser .jpeg");
            return;
        }
        
        validarImagen = true;
        JOptionPane.showMessageDialog(this, "La ruta de la imagen es correcta");
    }//GEN-LAST:event_btnValidarImagenActionPerformed

    private void btnNoEsInvolucradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoEsInvolucradoActionPerformed
        modificarVistaComponentesMusculo(false);
    }//GEN-LAST:event_btnNoEsInvolucradoActionPerformed

    private void btnSiEsInvolucradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiEsInvolucradoActionPerformed
        modificarVistaComponentesMusculo(true);
    }//GEN-LAST:event_btnSiEsInvolucradoActionPerformed

    private void btnGuardarEjMusculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEjMusculoActionPerformed
        StringBuilder sbErrores = new StringBuilder();
        
        String descripcion = txtDescripcionEjMusculo.getText();
        if (descripcion == null || descripcion.isEmpty()) sbErrores.append("  - Descripción vacía\n");
        
        String activacion = txtActivacionEjMusculo.getText();
        if ((activacion == null || activacion.isEmpty()) || (Integer.parseInt(activacion) < 0 || Integer.parseInt(activacion) > 100)) sbErrores.append("  - Activación vacía o no comprendida entre 0-100");
        
        if (!sbErrores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Registro incorrecto:\n" + sbErrores.toString());
            return;
        }
                        
        // --- idEjercicio se añade al validar formulario contra bd ---        
        Musculo musculoSeleccionado = (Musculo) cbMusculos.getSelectedItem();
        if (musculosInvolucrados.stream().anyMatch(e -> e.getIdMusculo().equals(musculoSeleccionado.getId()))) {
            musculosInvolucrados.removeIf(e -> e.getIdMusculo().equals(musculoSeleccionado.getId()));
            JOptionPane.showMessageDialog(this, "Músculo actualizado correctamente");   
            return;         
        }        

        musculosInvolucrados.add(new EjercicioMusculo(null, musculoSeleccionado.getId(), descripcion, btnSiEsDirectoEjMusculo.isSelected(), Integer.valueOf(activacion)));        
        JOptionPane.showMessageDialog(this, "Músculo guardado correctamente");
    }//GEN-LAST:event_btnGuardarEjMusculoActionPerformed

    private void btnGuardarEjercicioMusculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEjercicioMusculosActionPerformed
        // Validar campos del formulario
        StringBuilder sbErrores = new StringBuilder();
        
        String nombre = txtNombreEjercicio.getText();
        if (nombre == null || nombre.trim().isEmpty()) sbErrores.append("  - Nombre vacío\n");
        
        String descripcion = txtDescripcionEjercicio.getText();
        if (descripcion == null || descripcion.trim().isEmpty()) sbErrores.append("  - Descripción vacía\n");
        
        if (!validarImagen) sbErrores.append("  - No se ha validado imagen\n");
        
        Integer pesoMinimo = txtPesoMinimo.getText().matches("^[0-9]+$") ? Integer.valueOf(txtPesoMinimo.getText()) : null;
        Integer pesoMaximo = txtPesoMaximo.getText().matches("^[0-9]+$") ? Integer.valueOf(txtPesoMaximo.getText()) : null;
        
        if (musculosInvolucrados.isEmpty()) sbErrores.append("  - No hay músculos involucrados\n");
        
        if (!sbErrores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Formulario incorrecto:\n" + sbErrores.toString());
            return;
        }
        
        Ejercicio ejercicio = new Ejercicio(null, nombre, descripcion, txtImagen.getText(), pesoMinimo, pesoMaximo);
        int filaSeleccionada = tblEjercicios.getSelectedRow();
        
        if (filaSeleccionada > 0 && esEjercicioSeleccionado) {
            // Actualizar
            Integer idEjercicio = (Integer) tableModel.getValueAt(filaSeleccionada, 0);
            
            if (idEjercicio == null) {
                JOptionPane.showMessageDialog(this, "Ejercicio seleccionado no válido.");
                return;
            }
            
            ejercicio.setId(idEjercicio);
            EjercicioService.update(idEjercicio, ejercicio);
            
            // Actualizar imagen solo si cambió la ruta
            String rutaImagenBd = (String) tableModel.getValueAt(filaSeleccionada, 2);
            if (rutaImagenBd == null || !rutaImagenBd.equals(txtImagen.getText())) {
                EjercicioService.addImagen(idEjercicio, new File(txtImagen.getText()));
            }
            
            // Reemplazar todos los músculos involucrados
            EjercicioMusculoService.deleteAll(idEjercicio);
            for (EjercicioMusculo musculoInvolucrado : musculosInvolucrados) {
                musculoInvolucrado.setIdEjercicio(idEjercicio);
                EjercicioMusculoService.add(musculoInvolucrado);
            }
            
        } else {
            // Insertar
            Ejercicio ejercicioCreado = EjercicioService.add(ejercicio);
            EjercicioService.addImagen(ejercicioCreado.getId(), new File(txtImagen.getText()));
            
            for (EjercicioMusculo musculoInvolucrado : musculosInvolucrados) {
                musculoInvolucrado.setIdEjercicio(ejercicioCreado.getId());
                EjercicioMusculoService.add(musculoInvolucrado);
            }
        }
        
        reiniciarCampos();
        recargarEjercicios();
        JOptionPane.showMessageDialog(this, "Ejercicio guardado correctamente");
    }//GEN-LAST:event_btnGuardarEjercicioMusculosActionPerformed

    private void mitemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSobreActionPerformed
        ayudaUtil.mostrarAyuda();
    }//GEN-LAST:event_mitemSobreActionPerformed

    private void mitemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitemSalirActionPerformed

    private void tblEjerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEjerciciosMouseClicked
        Integer idEjercicio = (Integer) tableModel.getValueAt(tblEjercicios.getSelectedRow(), 0);            
        if (idEjercicio == null) {
            esEjercicioSeleccionado = false;
            return;
        }

        // Mostar detalles
        if (evt.getClickCount() == 1) {            
                Ejercicio ejercicio = EjercicioService.get(idEjercicio);
            
                // Obtener músculos involucrados
                List<EjercicioMusculo> musculos = EjercicioMusculoService.getAll(idEjercicio);
            
                // Mostrar
                StringBuilder sb = new StringBuilder();
                sb.append("-- Ejercicio -- \n  - Nombre: ").append(ejercicio.getNombre()).append("\n");
                sb.append("  - Descripción: ").append(ejercicio.getDescripcion()).append("\n");
                sb.append("  - Ruta de imagen en servidor: ").append(ejercicio.getRutaImagen()).append("\n");
                sb.append("  - Peso minimo: ").append(ejercicio.getPesoMinimo()).append("\n");
                sb.append("  - Peso máximo: ").append(ejercicio.getPesoMaximo()).append("\n");
            
                sb.append("\n-- Músculos --\n");
                for (int i = 0; i < musculos.size(); i++) {
                    Musculo musculo = MusculoService.get(musculos.get(i).getIdMusculo());
                    sb.append("  <> Músculo: ").append(musculo.getNombre()).append("\n");
                    sb.append("    - Nombre: ").append(musculo.getNombre()).append("\n");
                    sb.append("    - Descripción: ").append(musculo.getDescripcion()).append("\n");
                    sb.append("    - Zona: ").append(musculo.getZona()).append("\n");
                    sb.append("    - Grupo: ").append(musculo.getGrupo()).append("\n");
                }            
            
                txtaDetallesEjercicio.setText(sb.toString());
            }
        
        // Mostrar en formulario
        if (evt.getClickCount() == 2) {            
            esEjercicioSeleccionado = true;
            cargarDatos = true;
                
            // Ejercicio
            Ejercicio ejercicio = EjercicioService.get(idEjercicio);                
            txtNombreEjercicio.setText(ejercicio.getNombre());
            txtDescripcionEjercicio.setText(ejercicio.getDescripcion());
            txtImagen.setText(ejercicio.getRutaImagen());
            txtPesoMinimo.setText(ejercicio.getPesoMinimo() != 0 ? String.valueOf(ejercicio.getPesoMinimo()) : "");
            txtPesoMaximo.setText(ejercicio.getPesoMaximo() != 0 ? String.valueOf(ejercicio.getPesoMaximo()) : "");
                
            // Músculos
            musculosInvolucrados = EjercicioMusculoService.getAll(idEjercicio);          
            cargarDatos = false;            
        }
    }//GEN-LAST:event_tblEjerciciosMouseClicked

    private void cbMusculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMusculosActionPerformed
        // Parece que no detecta cambios, se sustituye por **ItemStateChanged**        
    }//GEN-LAST:event_cbMusculosActionPerformed

    private void cbMusculosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMusculosItemStateChanged
        if (cargarDatos) return;
        
        if(evt.getStateChange() == ItemEvent.SELECTED) {            
            if (tblEjercicios.getSelectedRow() < 0) return;

            Integer idEjercicio = (Integer) tableModel.getValueAt(tblEjercicios.getSelectedRow(), 0);
            Musculo musculoSeleccionado = (Musculo) cbMusculos.getSelectedItem();
        
            if (idEjercicio != null) {
                if (musculosInvolucrados.stream().anyMatch(e -> e.getIdMusculo().equals(musculoSeleccionado.getId()))) { // comprueba si en lista algún idMusculo == idMusculo
                    EjercicioMusculo ejercicioMusculoSeleccionado = EjercicioMusculoService.get(idEjercicio, musculoSeleccionado.getId());                    
                    modificarVistaComponentesMusculo(true);
                    
                    txtDescripcionEjMusculo.setText(musculoSeleccionado.getDescripcion());
                    txtActivacionEjMusculo.setText(String.valueOf(ejercicioMusculoSeleccionado.getPorcentajeActivacion()));
                
                    if (ejercicioMusculoSeleccionado.getEsDirecto()) btnSiEsDirectoEjMusculo.setSelected(true);
                    else btnNoDirectoEjMusculo.setSelected(true);
                } else {
                    txtDescripcionEjMusculo.setText("");
                    txtActivacionEjMusculo.setText("");
                    btnNoDirectoEjMusculo.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_cbMusculosItemStateChanged

    private void btnEliminarEjMusculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEjMusculoActionPerformed
        // Se elimina musculo en memoria
        Musculo musculoSeleccionado = (Musculo) cbMusculos.getSelectedItem();
        musculosInvolucrados.removeIf(e -> e.getIdMusculo().equals(musculoSeleccionado.getId()));

        // Reiniciar campos
        txtDescripcionEjMusculo.setText("");
        txtActivacionEjMusculo.setText("");
        btnNoDirectoEjMusculo.setSelected(true);
        
        JOptionPane.showMessageDialog(this, "Se ha eliminado el músculo involucrado");
    }//GEN-LAST:event_btnEliminarEjMusculoActionPerformed

    private void btnEliminarEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEjercicioActionPerformed
        int filaSeleccionada = tblEjercicios.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un ejercicio en la tabla antes de eliminar.");
            return;
        }
        
        Integer idEjercicio = (Integer) tableModel.getValueAt(filaSeleccionada, 0);
        if (idEjercicio != null)  {
            EjercicioService.deleteImagen(idEjercicio);
            EjercicioService.delete(idEjercicio);
            recargarEjercicios();
        }
    }//GEN-LAST:event_btnEliminarEjercicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException e) {
            System.err.println("Error: " + e);
            // logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEjMusculo;
    private javax.swing.JButton btnEliminarEjercicio;
    private javax.swing.JButton btnGuardarEjMusculo;
    private javax.swing.JButton btnGuardarEjercicioMusculos;
    private javax.swing.JRadioButton btnNoDirectoEjMusculo;
    private javax.swing.JRadioButton btnNoEsInvolucrado;
    private javax.swing.JRadioButton btnSiEsDirectoEjMusculo;
    private javax.swing.JRadioButton btnSiEsInvolucrado;
    private javax.swing.JToggleButton btnValidarImagen;
    private javax.swing.ButtonGroup btngEsDirecto;
    private javax.swing.ButtonGroup btngEsInvolucrado;
    private javax.swing.JComboBox<Musculo> cbMusculos;
    private javax.swing.JLabel lbDescripcionEjercicio;
    private javax.swing.JLabel lblActivacionEjMusculo;
    private javax.swing.JLabel lblCbMusculos;
    private javax.swing.JLabel lblDescripcionEjMusculo;
    private javax.swing.JLabel lblDetallesEjercicio;
    private javax.swing.JLabel lblEjercicio;
    private javax.swing.JLabel lblEjerciciosCargados;
    private javax.swing.JLabel lblEsDirectoEjMusculo;
    private javax.swing.JLabel lblEsInvolucrado;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMusculos;
    private javax.swing.JLabel lblNombreEjercicio;
    private javax.swing.JLabel lblPesoMaximo;
    private javax.swing.JLabel lblPesoMinimo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mitemSalir;
    private javax.swing.JMenuItem mitemSobre;
    private javax.swing.JPanel pnlEjercicio;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlMusculos;
    private javax.swing.JScrollPane spDetallesEjercicio;
    private javax.swing.JScrollPane spEjercicios;
    private javax.swing.JTable tblEjercicios;
    private javax.swing.JTextField txtActivacionEjMusculo;
    private javax.swing.JTextField txtDescripcionEjMusculo;
    private javax.swing.JTextField txtDescripcionEjercicio;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombreEjercicio;
    private javax.swing.JTextField txtPesoMaximo;
    private javax.swing.JTextField txtPesoMinimo;
    private javax.swing.JTextArea txtaDetallesEjercicio;
    // End of variables declaration//GEN-END:variables
}
