/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.sergiopt.formulario;

import es.sergiopt.models.Ejercicio;
import es.sergiopt.models.EjercicioMusculo;
import es.sergiopt.models.Musculo;
import es.sergiopt.services.EjercicioMusculosService;
import es.sergiopt.services.EjercicioService;
import es.sergiopt.services.MusculoService;
import java.awt.event.ItemEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import es.sergiopt.utils.AyudaUtil;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sergiopt
 */
public class FormularioPrincipal extends javax.swing.JFrame {       
    
    private final AyudaUtil ayudaUtil;
    
    private DefaultTableModel tableModel;    
    private List<EjercicioMusculo> musculosInvolucrados;    
    private Boolean esEjercicioSeleccionado;        
    
    /**
     * Creates new form Formulario
     */
    public FormularioPrincipal() {
        // Inicializaciones
        musculosInvolucrados = new ArrayList<>();
        esEjercicioSeleccionado = false;        
        
        // Componentes
        initComponents();
        
        tableModel = new DefaultTableModel();
        tableModel = (DefaultTableModel) tblEjercicios.getModel();
        
        // Cargar músculos en combo box
        List<Musculo> musculos = new ArrayList();
        Musculo seleccionar = new Musculo();
        seleccionar.setNombre("Seleccionar");
        musculos.add(seleccionar);
        musculos.addAll(MusculoService.getAll());
        for (Musculo musculo : musculos) 
            cbMusculos.addItem(musculo);                        
        
        ayudaUtil = new AyudaUtil();

        // Cargar ejercicios en tabla
        List<Ejercicio> ejercicios = EjercicioService.getAll();
        for (Ejercicio ejercicio : ejercicios) {
            Object[] row = {ejercicio.getIdEjercicio(), ejercicio.getNombre(), ejercicio.getRutaImagen(), ejercicio.getPesoMinimo(), ejercicio.getPesoMaximo()};
            tableModel.addRow(row);
        }
    }
    
    private void reiniciarCampos() {
        txtNombreEjercicio.setText("");
        txtDescripcionEjercicio.setText("");
        txtImagen.setText("");
        txtPesoMinimo.setText("");
        txtPesoMaximo.setText("");
        cbMusculos.setSelectedIndex(0);
        txtDescripcionEjMusculo.setText("");
        txtActivacionEjMusculo.setText("");
        btnNoDirectoEjMusculo.setSelected(true);
        txtaDetallesEjercicio.setText("");
        
        modificarVistaComponentesMusculo(false);
        musculosInvolucrados = new ArrayList<>();
    }
    
    private void recargarEjercicios() {
        tableModel.setRowCount(1); // sigue conteniendo vacía
        List<Ejercicio> ejercicios = EjercicioService.getAll();
        for (Ejercicio ejercicio : ejercicios) {
            Object[] row = {ejercicio.getIdEjercicio(), ejercicio.getNombre(), ejercicio.getRutaImagen()};
            tableModel.addRow(row);
        }
    }
    
    private void modificarVistaComponentesMusculo(boolean esHabilitado) {
        txtDescripcionEjMusculo.setEnabled(esHabilitado);
        txtActivacionEjMusculo.setEnabled(esHabilitado);
        btnNoDirectoEjMusculo.setEnabled(esHabilitado);
        btnSiEsDirectoEjMusculo.setEnabled(esHabilitado);
        btnGuardarEjMusculo.setEnabled(esHabilitado);
        btnEliminarEjMusculo.setEnabled(esHabilitado);
    }              
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngEsInvolucrado = new javax.swing.ButtonGroup();
        btngEsDirecto = new javax.swing.ButtonGroup();
        lblEjercicio = new javax.swing.JLabel();
        pnlEjercicio = new javax.swing.JPanel();
        lblNombreEjercicio = new javax.swing.JLabel();
        txtNombreEjercicio = new javax.swing.JTextField();
        lbDescripcionEjercicio = new javax.swing.JLabel();
        txtDescripcionEjercicio = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        btnElegirImagen = new javax.swing.JToggleButton();
        lblPesoMinimo = new javax.swing.JLabel();
        txtPesoMinimo = new javax.swing.JTextField();
        lblPesoMaximo = new javax.swing.JLabel();
        txtPesoMaximo = new javax.swing.JTextField();
        lblMusculos = new javax.swing.JLabel();
        pnlMusculos = new javax.swing.JPanel();
        lblCbMusculos = new javax.swing.JLabel();
        cbMusculos = new javax.swing.JComboBox<>();
        lblEsInvolucrado = new javax.swing.JLabel();
        btnNoEsInvolucrado = new javax.swing.JRadioButton();
        btnSiEsInvolucrado = new javax.swing.JRadioButton();
        lblDescripcionEjMusculo = new javax.swing.JLabel();
        txtDescripcionEjMusculo = new javax.swing.JTextField();
        lblActivacionEjMusculo = new javax.swing.JLabel();
        txtActivacionEjMusculo = new javax.swing.JTextField();
        lblPorcentajeActivacionEjMusculo = new javax.swing.JLabel();
        lblEsDirectoEjMusculo = new javax.swing.JLabel();
        btnNoDirectoEjMusculo = new javax.swing.JRadioButton();
        btnSiEsDirectoEjMusculo = new javax.swing.JRadioButton();
        btnGuardarEjMusculo = new javax.swing.JButton();
        btnEliminarEjMusculo = new javax.swing.JButton();
        btnGuardarFormulario = new javax.swing.JButton();
        lblEjerciciosCargados = new javax.swing.JLabel();
        spEjercicios = new javax.swing.JScrollPane();
        tblEjercicios = new javax.swing.JTable();
        btnEliminarEjercicio = new javax.swing.JButton();
        lblDetallesEjercicio = new javax.swing.JLabel();
        spDetallesEjercicio = new javax.swing.JScrollPane();
        txtaDetallesEjercicio = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        menuEditar = new javax.swing.JMenu();
        mitemEditarMusculos = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        mitemSobre = new javax.swing.JMenuItem();
        mitemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración Ejercicios Gym");
        setMinimumSize(new java.awt.Dimension(900, 600));

        lblEjercicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEjercicio.setText("Ejercicio");

        pnlEjercicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreEjercicio.setText("Nombre");

        lbDescripcionEjercicio.setText("Descripción");

        lblImagen.setText("Imagen");

        txtImagen.setEditable(false);

        btnElegirImagen.setText("Elegir imagen");
        btnElegirImagen.addActionListener(this::btnElegirImagenActionPerformed);

        lblPesoMinimo.setText("Peso minimo");

        lblPesoMaximo.setText("Peso máximo");

        javax.swing.GroupLayout pnlEjercicioLayout = new javax.swing.GroupLayout(pnlEjercicio);
        pnlEjercicio.setLayout(pnlEjercicioLayout);
        pnlEjercicioLayout.setHorizontalGroup(
            pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjercicioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEjercicioLayout.createSequentialGroup()
                        .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEjercicioLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbDescripcionEjercicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addComponent(lblNombreEjercicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlEjercicioLayout.createSequentialGroup()
                                .addComponent(txtImagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnElegirImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreEjercicio)
                            .addComponent(txtDescripcionEjercicio)))
                    .addGroup(pnlEjercicioLayout.createSequentialGroup()
                        .addComponent(lblPesoMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesoMinimo)
                        .addGap(18, 18, 18)
                        .addComponent(lblPesoMaximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesoMaximo)))
                .addGap(20, 20, 20))
        );
        pnlEjercicioLayout.setVerticalGroup(
            pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjercicioLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEjercicio)
                    .addComponent(lblNombreEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionEjercicio)
                    .addComponent(lbDescripcionEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImagen)
                    .addComponent(btnElegirImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(pnlEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesoMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesoMinimo)
                    .addComponent(lblPesoMaximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesoMaximo))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lblMusculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMusculos.setText("Músculos involucrados");

        pnlMusculos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCbMusculos.setText("Músculo");

        cbMusculos.setMaximumSize(new java.awt.Dimension(32767, 200));
        cbMusculos.addItemListener(this::cbMusculosItemStateChanged);
        cbMusculos.addActionListener(this::cbMusculosActionPerformed);

        lblEsInvolucrado.setText("Es involucrado");

        btngEsInvolucrado.add(btnNoEsInvolucrado);
        btnNoEsInvolucrado.setSelected(true);
        btnNoEsInvolucrado.setText("No");
        btnNoEsInvolucrado.addActionListener(this::btnNoEsInvolucradoActionPerformed);

        btngEsInvolucrado.add(btnSiEsInvolucrado);
        btnSiEsInvolucrado.setText("Si");
        btnSiEsInvolucrado.addActionListener(this::btnSiEsInvolucradoActionPerformed);

        lblDescripcionEjMusculo.setText("Descipción");

        txtDescripcionEjMusculo.setEnabled(false);

        lblActivacionEjMusculo.setText("Porcentaje activación");

        txtActivacionEjMusculo.setEnabled(false);
        txtActivacionEjMusculo.setMinimumSize(new java.awt.Dimension(64, 40));

        lblPorcentajeActivacionEjMusculo.setText("(0-100)");

        lblEsDirectoEjMusculo.setText("Es directo");

        btngEsDirecto.add(btnNoDirectoEjMusculo);
        btnNoDirectoEjMusculo.setSelected(true);
        btnNoDirectoEjMusculo.setText("No");
        btnNoDirectoEjMusculo.setEnabled(false);

        btngEsDirecto.add(btnSiEsDirectoEjMusculo);
        btnSiEsDirectoEjMusculo.setText("Si");
        btnSiEsDirectoEjMusculo.setEnabled(false);

        btnGuardarEjMusculo.setText("Guardar músculo");
        btnGuardarEjMusculo.setEnabled(false);
        btnGuardarEjMusculo.addActionListener(this::btnGuardarEjMusculoActionPerformed);

        btnEliminarEjMusculo.setText("Eliminar músculo");
        btnEliminarEjMusculo.setEnabled(false);
        btnEliminarEjMusculo.addActionListener(this::btnEliminarEjMusculoActionPerformed);

        javax.swing.GroupLayout pnlMusculosLayout = new javax.swing.GroupLayout(pnlMusculos);
        pnlMusculos.setLayout(pnlMusculosLayout);
        pnlMusculosLayout.setHorizontalGroup(
            pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMusculosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMusculosLayout.createSequentialGroup()
                        .addComponent(lblActivacionEjMusculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActivacionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPorcentajeActivacionEjMusculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(lblEsDirectoEjMusculo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNoDirectoEjMusculo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiEsDirectoEjMusculo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(pnlMusculosLayout.createSequentialGroup()
                        .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCbMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDescripcionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMusculosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDescripcionEjMusculo))
                            .addGroup(pnlMusculosLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cbMusculos, 0, 155, Short.MAX_VALUE)
                                .addGap(51, 51, 51)
                                .addComponent(lblEsInvolucrado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNoEsInvolucrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiEsInvolucrado)))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMusculosLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnEliminarEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        pnlMusculosLayout.setVerticalGroup(
            pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusculosLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMusculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCbMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNoEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSiEsInvolucrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionEjMusculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActivacionEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtActivacionEjMusculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEsDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNoDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSiEsDirectoEjMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPorcentajeActivacionEjMusculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlMusculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEjMusculo)
                    .addComponent(btnEliminarEjMusculo))
                .addContainerGap())
        );

        btnGuardarFormulario.setText("Guardar fornulario");
        btnGuardarFormulario.addActionListener(this::btnGuardarFormularioActionPerformed);

        lblEjerciciosCargados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEjerciciosCargados.setText("Ejercicios cargados");

        tblEjercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEjercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEjerciciosMouseClicked(evt);
            }
        });
        spEjercicios.setViewportView(tblEjercicios);

        btnEliminarEjercicio.setText("Eliminar ejercicio");
        btnEliminarEjercicio.addActionListener(this::btnEliminarEjercicioActionPerformed);

        lblDetallesEjercicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDetallesEjercicio.setText("Detalles del ejercicio");

        txtaDetallesEjercicio.setEditable(false);
        txtaDetallesEjercicio.setColumns(20);
        txtaDetallesEjercicio.setRows(5);
        spDetallesEjercicio.setViewportView(txtaDetallesEjercicio);

        menuEditar.setText("Editar");

        mitemEditarMusculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitemEditarMusculos.setText("Editar músculos");
        mitemEditarMusculos.addActionListener(this::mitemEditarMusculosActionPerformed);
        menuEditar.add(mitemEditarMusculos);

        menuBar.add(menuEditar);

        menuAyuda.setText("Ayuda");

        mitemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitemSobre.setText("Sobre");
        mitemSobre.addActionListener(this::mitemSobreActionPerformed);
        menuAyuda.add(mitemSobre);

        mitemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitemSalir.setText("Salir");
        mitemSalir.addActionListener(this::mitemSalirActionPerformed);
        menuAyuda.add(mitemSalir);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEjerciciosCargados)
                    .addComponent(lblDetallesEjercicio)
                    .addComponent(spEjercicios, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(spDetallesEjercicio)
                    .addComponent(btnEliminarEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEjerciciosCargados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spEjercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEjercicio)
                        .addGap(18, 18, 18)
                        .addComponent(lblDetallesEjercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spDetallesEjercicio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47)
                        .addComponent(lblMusculos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarFormulario)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	private void btnElegirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirImagenActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "jpeg"));

        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File imagen = chooser.getSelectedFile();
            txtImagen.setText(imagen.getAbsolutePath());
        }
    }//GEN-LAST:event_btnElegirImagenActionPerformed
	
	private void btnEliminarEjMusculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEjMusculoActionPerformed
        // Se elimina musculo en memoria
        Musculo musculoSeleccionado = (Musculo) cbMusculos.getSelectedItem();
        musculosInvolucrados.removeIf(e -> e.getIdMusculo().equals(musculoSeleccionado.getIdMusculo()));

        // Reiniciar campos
        txtDescripcionEjMusculo.setText("");
        txtActivacionEjMusculo.setText("");
        btnNoDirectoEjMusculo.setSelected(true);

        JOptionPane.showMessageDialog(this, "Se ha eliminado el músculo involucrado");
    }//GEN-LAST:event_btnEliminarEjMusculoActionPerformed
	
	private void btnGuardarEjMusculoActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        StringBuilder sbErrores = new StringBuilder();

        String descripcion = txtDescripcionEjMusculo.getText();
        if (descripcion == null || descripcion.isEmpty()) sbErrores.append("  - Descripción vacía\n");

        String activacion = txtActivacionEjMusculo.getText();
        if ((activacion == null || activacion.isEmpty()) || (Integer.parseInt(activacion) < 0 || Integer.parseInt(activacion) > 100)) sbErrores.append("  - Activación vacía o no comprendida entre 0-100");

        if (!sbErrores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Registro incorrecto:\n" + sbErrores.toString());
            return;
        }

        // -- idEjercicio se añade al validar formulario contra bd --
        Musculo musculoSeleccionado = (Musculo) cbMusculos.getSelectedItem();
        if (musculosInvolucrados.stream().anyMatch(e -> e.getIdMusculo().equals(musculoSeleccionado.getIdMusculo()))) {
            musculosInvolucrados.removeIf(e -> e.getIdMusculo().equals(musculoSeleccionado.getIdMusculo()));
            musculosInvolucrados.add(new EjercicioMusculo(null, musculoSeleccionado.getIdMusculo(), descripcion, btnSiEsDirectoEjMusculo.isSelected(), Integer.valueOf(activacion)));
            JOptionPane.showMessageDialog(this, "Músculo actualizado correctamente");
            return;
        }

        musculosInvolucrados.add(new EjercicioMusculo(null, musculoSeleccionado.getIdMusculo(), descripcion, btnSiEsDirectoEjMusculo.isSelected(), Integer.valueOf(activacion)));
        JOptionPane.showMessageDialog(this, "Músculo guardado correctamente");
    }                                                           
	
	private StringBuilder validarCamposDeFormulario() throws Exception {
        StringBuilder sbErrores = new StringBuilder();

            String nombre = txtNombreEjercicio.getText();
            if (nombre == null || nombre.isEmpty())
                sbErrores.append("  - Nombre vacío\n");

            String descripcion = txtDescripcionEjercicio.getText();
            if (descripcion == null || descripcion.isEmpty())
                sbErrores.append("  - Descripción vacía\n");

            if (txtImagen == null || txtImagen.getText().isEmpty())
                sbErrores.append("  - No se ha validado imagen\n");

            Integer pesoMinimo = null;
            Integer pesoMaximo = null;
            try {
                pesoMinimo = txtPesoMinimo.getText().matches("^[0-9]+$") ? Integer.valueOf(txtPesoMinimo.getText()) : null;
                pesoMaximo = txtPesoMaximo.getText().matches("^[0-9]+$") ? Integer.valueOf(txtPesoMaximo.getText()) : null;

            } catch (NumberFormatException e) {
                sbErrores.append("Peso minimo y peso máximo deben contenedor unicamente números\n");
            }
        
            if (musculosInvolucrados.isEmpty())
                sbErrores.append("  - No hay músculos involucrados\n");
            
            return sbErrores;
    }
    
    private void insertarFormulario(Ejercicio ejercicio) throws Exception {
        Ejercicio ejercicioCreado = EjercicioService.add(ejercicio);
        EjercicioService.addImagen(ejercicioCreado.getIdEjercicio(), new File(txtImagen.getText()));
                
        for (EjercicioMusculo musculoInvolucrado : musculosInvolucrados) {
            musculoInvolucrado.setIdEjercicio(ejercicioCreado.getIdEjercicio());
            EjercicioMusculosService.add(musculoInvolucrado);
        }
        
        JOptionPane.showMessageDialog(this, "Ejercicio guardado correctamente");
    }
    
    private void actualizarFormulario(Ejercicio ejercicio, int filaSeleccionada) throws Exception {
        Integer idEjercicio = (Integer) tableModel.getValueAt(filaSeleccionada, 0);

       if (idEjercicio == null) {
            JOptionPane.showMessageDialog(this, "Ejercicio seleccionado no válido.");
            return;
        }

        ejercicio.setIdEjercicio(idEjercicio);
        EjercicioService.update(idEjercicio, ejercicio);

        // Actualizar imagen solo si cambió la ruta
        String rutaImagenBd = (String) tableModel.getValueAt(filaSeleccionada, 2);
        if (rutaImagenBd == null || !rutaImagenBd.equals(txtImagen.getText()))
            EjercicioService.addImagen(idEjercicio, new File(txtImagen.getText()));

        // Reemplazar músculos involucrados              
        List<EjercicioMusculo> musculosInvolucradosBd = EjercicioMusculosService.getAll(idEjercicio);
        for (EjercicioMusculo musculoInvolucrado : musculosInvolucrados) {
            // INSERTAR
            if (!musculosInvolucradosBd.stream().anyMatch(e -> e.getIdMusculo().equals(musculoInvolucrado.getIdMusculo()))) {
                musculoInvolucrado.setIdEjercicio(ejercicio.getIdEjercicio());
                EjercicioMusculosService.add(musculoInvolucrado);
            // ACTUALIZAR
            } else
                EjercicioMusculosService.update(ejercicio.getIdEjercicio(), musculoInvolucrado.getIdMusculo(), musculoInvolucrado);                
        }
        
        // ELIMINAR
        for (EjercicioMusculo musculoInvolucradoBd : musculosInvolucradosBd) {
            if (!musculosInvolucrados.stream().anyMatch(e -> e.getIdMusculo().equals(musculoInvolucradoBd.getIdMusculo())))
                EjercicioMusculosService.delete(idEjercicio, musculoInvolucradoBd.getIdMusculo());            
        }
        
        JOptionPane.showMessageDialog(this, "Ejercicio actualizado correctamente");
    }        
	
	private void btnGuardarFormularioActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        try {            
            StringBuilder sbErrores = validarCamposDeFormulario();
            if (!sbErrores.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Formulario incorrecto:\n" + sbErrores.toString());
                return;
            }

            Integer pesoMinimo = txtPesoMinimo.getText().matches("^[0-9]+$") ? Integer.valueOf(txtPesoMinimo.getText()) : null;
            Integer pesoMaximo = txtPesoMaximo.getText().matches("^[0-9]+$") ? Integer.valueOf(txtPesoMaximo.getText()) : null;
            
            Ejercicio ejercicio = new Ejercicio(null, txtNombreEjercicio.getText(), txtDescripcionEjercicio.getText(), txtImagen.getText(), pesoMinimo, pesoMaximo);
            int filaSeleccionada = tblEjercicios.getSelectedRow();

            if (filaSeleccionada > 0 && esEjercicioSeleccionado)
                actualizarFormulario(ejercicio, filaSeleccionada);
            else
                insertarFormulario(ejercicio);
        
            reiniciarCampos();
            recargarEjercicios();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido algún error desconocido al intentar guardar el formulario");
            System.err.println("Error al guardar el formulario: " + e.getMessage());
            e.printStackTrace();
        }
    }                                                        
	
	private void btnEliminarEjercicioActionPerformed(java.awt.event.ActionEvent evt) {                                                     
            int filaSeleccionada = tblEjercicios.getSelectedRow();
            if (filaSeleccionada < 1) {
                JOptionPane.showMessageDialog(this, "Seleccione un ejercicio en la tabla antes de eliminar.");
                return;
            }
            
            int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar el ejercicio?");            
            if (opcion == JOptionPane.YES_OPTION) {                        
                Integer idEjercicio = (Integer) tableModel.getValueAt(filaSeleccionada, 0);
                if (idEjercicio != null)  {
                    EjercicioService.deleteImagen(idEjercicio);
                    EjercicioService.delete(idEjercicio);            
                    recargarEjercicios();
                    JOptionPane.showMessageDialog(this, "Se ha eliminado el músculo seleccionado");
                }
            }
        }                                                         
	
    private void btnNoEsInvolucradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoEsInvolucradoActionPerformed
        modificarVistaComponentesMusculo(false);
    }//GEN-LAST:event_btnNoEsInvolucradoActionPerformed

    private void btnSiEsInvolucradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiEsInvolucradoActionPerformed
        modificarVistaComponentesMusculo(true);
    }//GEN-LAST:event_btnSiEsInvolucradoActionPerformed
	
	 private void cbMusculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMusculosActionPerformed
        // Parece que no detecta cambios, se sustituye por **ItemStateChanged**        
    }//GEN-LAST:event_cbMusculosActionPerformed

    private void cbMusculosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMusculosItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {            
            if (tblEjercicios.getSelectedRow() < 0) return;

            Integer idEjercicio = (Integer) tableModel.getValueAt(tblEjercicios.getSelectedRow(), 0);
            Musculo musculoSeleccionado = (Musculo) cbMusculos.getSelectedItem();
        
            // Rellena INFORMACIÓN de músculo involucrado
            if (idEjercicio != null) {
                if (musculosInvolucrados.stream().anyMatch(e -> e.getIdMusculo().equals(musculoSeleccionado.getIdMusculo()))) { // comprueba si en lista algún idMusculo == idMusculo
                    EjercicioMusculo ejercicioMusculoSeleccionado = EjercicioMusculosService.get(idEjercicio, musculoSeleccionado.getIdMusculo());                    
                    modificarVistaComponentesMusculo(true);
                    
                    txtDescripcionEjMusculo.setText(musculoSeleccionado.getDescripcion());
                    txtActivacionEjMusculo.setText(String.valueOf(ejercicioMusculoSeleccionado.getPorcentajeActivacion()));
                
                    if (ejercicioMusculoSeleccionado.getEsDirecto()) btnSiEsDirectoEjMusculo.setSelected(true);
                    else btnNoDirectoEjMusculo.setSelected(true);
                } else {
                    txtDescripcionEjMusculo.setText("");
                    txtActivacionEjMusculo.setText("");
                    btnNoDirectoEjMusculo.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_cbMusculosItemStateChanged
	
	private void tblEjerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEjerciciosMouseClicked
        Integer idEjercicio = (Integer) tableModel.getValueAt(tblEjercicios.getSelectedRow(), 0);            
        if (evt.getClickCount() == 1 && idEjercicio == null) {
            txtaDetallesEjercicio.setText("");
            esEjercicioSeleccionado = false;
            return;
        }

        if (evt.getClickCount() == 2 && idEjercicio == null) {
            reiniciarCampos();
            esEjercicioSeleccionado = false;
            return;
        }
        
        // Mostar detalles
        Ejercicio ejercicio = EjercicioService.get(idEjercicio);
        if (evt.getClickCount() == 1) {            
                // Obtener músculos involucrados
                List<EjercicioMusculo> musculos = EjercicioMusculosService.getAll(idEjercicio);
            
                // Mostrar
                StringBuilder sb = new StringBuilder();
                sb.append("<> Ejercicio\n  - Nombre: ").append(ejercicio.getNombre()).append("\n");
                sb.append("  - Descripción: ").append(ejercicio.getDescripcion()).append("\n");
                sb.append("  - Ruta de imagen en servidor: ").append(ejercicio.getRutaImagen()).append("\n");
                sb.append("  - Peso minimo: ").append(ejercicio.getPesoMinimo()).append("\n");
                sb.append("  - Peso máximo: ").append(ejercicio.getPesoMaximo()).append("\n");
            
                sb.append("\n<> Músculos\n");
                for (int i = 0; i < musculos.size(); i++) {
                    Musculo musculo = MusculoService.get(musculos.get(i).getIdMusculo());
                    sb.append("  • ").append(musculo.getNombre()).append("\n");
                    sb.append("    - Descripción: ").append(musculo.getDescripcion()).append("\n");
                    sb.append("    - Zona: ").append(musculo.getZona()).append("\n");
                    sb.append("    - Grupo: ").append(musculo.getGrupo()).append("\n");
                }            
            
                txtaDetallesEjercicio.setText(sb.toString());
            }
        
        // Mostrar en formulario
        if (evt.getClickCount() == 2) {            
            esEjercicioSeleccionado = true;
            txtNombreEjercicio.setText(ejercicio.getNombre());
            txtDescripcionEjercicio.setText(ejercicio.getDescripcion());
            txtImagen.setText(ejercicio.getRutaImagen());
            txtPesoMinimo.setText(ejercicio.getPesoMinimo() != null && ejercicio.getPesoMinimo() != 0 ? String.valueOf(ejercicio.getPesoMinimo()) : "");
            txtPesoMaximo.setText(ejercicio.getPesoMaximo() != null && ejercicio.getPesoMaximo() != 0 ? String.valueOf(ejercicio.getPesoMaximo()) : "");
                
            // Músculos
            musculosInvolucrados = EjercicioMusculosService.getAll(idEjercicio);                   
        }
    }//GEN-LAST:event_tblEjerciciosMouseClicked
	
	private void mitemEditarMusculosActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        FormularioMusculos formularioMusculos = new FormularioMusculos(this, true);
        formularioMusculos.setVisible(true);
        
        // Refrescar combo box de musculos
        cbMusculos.removeAllItems();        
        List<Musculo> musculos = new ArrayList();
        Musculo seleccionar = new Musculo();
        seleccionar.setNombre("Seleccionar");
        musculos.add(seleccionar);
        
        musculos.addAll(MusculoService.getAll());
        for (Musculo musculo : musculos) 
            cbMusculos.addItem(musculo);  
    }                                                         
	
    private void mitemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSobreActionPerformed
        ayudaUtil.mostrarAyuda();
    }//GEN-LAST:event_mitemSobreActionPerformed

    private void mitemSalirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.exit(0);
    }                                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException e) {
            System.err.println("Error: " + e);
            // logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnElegirImagen;
    private javax.swing.JButton btnEliminarEjMusculo;
    private javax.swing.JButton btnEliminarEjercicio;
    private javax.swing.JButton btnGuardarEjMusculo;
    private javax.swing.JButton btnGuardarFormulario;
    private javax.swing.JRadioButton btnNoDirectoEjMusculo;
    private javax.swing.JRadioButton btnNoEsInvolucrado;
    private javax.swing.JRadioButton btnSiEsDirectoEjMusculo;
    private javax.swing.JRadioButton btnSiEsInvolucrado;
    private javax.swing.ButtonGroup btngEsDirecto;
    private javax.swing.ButtonGroup btngEsInvolucrado;
    private javax.swing.JComboBox<Musculo> cbMusculos;
    private javax.swing.JLabel lbDescripcionEjercicio;
    private javax.swing.JLabel lblActivacionEjMusculo;
    private javax.swing.JLabel lblCbMusculos;
    private javax.swing.JLabel lblDescripcionEjMusculo;
    private javax.swing.JLabel lblDetallesEjercicio;
    private javax.swing.JLabel lblEjercicio;
    private javax.swing.JLabel lblEjerciciosCargados;
    private javax.swing.JLabel lblEsDirectoEjMusculo;
    private javax.swing.JLabel lblEsInvolucrado;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMusculos;
    private javax.swing.JLabel lblNombreEjercicio;
    private javax.swing.JLabel lblPesoMaximo;
    private javax.swing.JLabel lblPesoMinimo;
    private javax.swing.JLabel lblPorcentajeActivacionEjMusculo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem mitemEditarMusculos;
    private javax.swing.JMenuItem mitemSalir;
    private javax.swing.JMenuItem mitemSobre;
    private javax.swing.JPanel pnlEjercicio;
    private javax.swing.JPanel pnlMusculos;
    private javax.swing.JScrollPane spDetallesEjercicio;
    private javax.swing.JScrollPane spEjercicios;
    private javax.swing.JTable tblEjercicios;
    private javax.swing.JTextField txtActivacionEjMusculo;
    private javax.swing.JTextField txtDescripcionEjMusculo;
    private javax.swing.JTextField txtDescripcionEjercicio;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombreEjercicio;
    private javax.swing.JTextField txtPesoMaximo;
    private javax.swing.JTextField txtPesoMinimo;
    private javax.swing.JTextArea txtaDetallesEjercicio;
    // End of variables declaration//GEN-END:variables
}
