/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package es.sergiopt.formulario;

import es.sergiopt.services.MusculoService;
import javax.swing.table.DefaultTableModel;

import es.sergiopt.models.Musculo;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author sergiopt
 */
public class FormularioMusculos extends javax.swing.JDialog {
    
    private DefaultTableModel tableModel;    
    private Boolean esMusculoSeleccionado;
    
    /**
     * Creates new form FormularioMusculos
     */
    public FormularioMusculos(java.awt.Frame parent, boolean modal) {                
        super(parent, modal);
        
        esMusculoSeleccionado = false;
        
        initComponents();
        
        tableModel = new DefaultTableModel();
        tableModel = (DefaultTableModel) tblMusculos.getModel();
        
        // Cargar músculos
        List<Musculo> musculos = MusculoService.getAll();
        for (Musculo musculo : musculos) {
            Object[] row = {musculo.getIdMusculo(), musculo.getNombre()};
            tableModel.addRow(row);
        }
    }

    private void reiniciarCampos() {
        txtNombre.setText("");
        txtDescripcion.setText("");
        cbZona.setSelectedItem("Seleccionar");
        cbGrupo.setSelectedItem("Seleccionar");
    }
    
    
    private void recargarMusculos() {
        tableModel.setRowCount(1);
        List<Musculo> musculos = MusculoService.getAll();
        for (Musculo musculo : musculos) {
            Object[] row = {musculo.getIdMusculo(), musculo.getNombre()};
            tableModel.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarMusculo = new javax.swing.JButton();
        btnGuardarMusculo = new javax.swing.JButton();
        lblDetalles = new javax.swing.JLabel();
        spTblMusculos = new javax.swing.JScrollPane();
        tblMusculos = new javax.swing.JTable();
        spDetalles = new javax.swing.JScrollPane();
        txtaDetalles = new javax.swing.JTextArea();
        pnlFormulario = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cbZona = new javax.swing.JComboBox<>();
        lblZona = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        cbGrupo = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(640, 360));

        btnEliminarMusculo.setText("Eliminar músculo");
        btnEliminarMusculo.addActionListener(this::btnEliminarMusculoActionPerformed);

        btnGuardarMusculo.setText("Guardar músculo");
        btnGuardarMusculo.addActionListener(this::btnGuardarMusculoActionPerformed);

        lblDetalles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDetalles.setText("Detalles");

        tblMusculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMusculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMusculosMouseClicked(evt);
            }
        });
        spTblMusculos.setViewportView(tblMusculos);

        txtaDetalles.setEditable(false);
        txtaDetalles.setColumns(20);
        txtaDetalles.setRows(5);
        spDetalles.setViewportView(txtaDetalles);

        pnlFormulario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlFormulario.setPreferredSize(new java.awt.Dimension(300, 100));

        lblNombre.setText("Nombre");

        cbZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SUPERIOR", "INFERIOR", "CORE" }));

        lblZona.setText("Zona");

        lblGrupo.setText("Grupo");

        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "PECHO", "ESPALDA", "HOMBRO", "BRAZO", "LUMBARES", "ABDOMINALES", "PIERNA" }));

        lblDescripcion.setText("Descripción");

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(lblZona)
                    .addComponent(lblGrupo)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbZona, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGrupo, 0, 207, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZona)
                    .addComponent(cbZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupo)
                    .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spDetalles)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminarMusculo, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDetalles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spTblMusculos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnGuardarMusculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTblMusculos, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addComponent(lblDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarMusculo)
                    .addComponent(btnGuardarMusculo))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMusculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMusculoActionPerformed
        int filaSeleccionada = tblMusculos.getSelectedRow();
        if (filaSeleccionada < 1) {
            JOptionPane.showMessageDialog(this, "Seleccione un músculo en la tabla antes de eliminar.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar el músculo?");   
        if (opcion == JOptionPane.YES_OPTION) {
            Integer idMusculo = (Integer) tableModel.getValueAt(filaSeleccionada, 0);
            if (idMusculo != null)  {
                MusculoService.delete(idMusculo);            
                recargarMusculos();
                JOptionPane.showMessageDialog(this, "Se ha eliminado el músculo seleccionado");
            }      
        }        
    }//GEN-LAST:event_btnEliminarMusculoActionPerformed

    private void btnGuardarMusculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMusculoActionPerformed
	try {
            StringBuilder sbErrores = new StringBuilder();
		
            String nombre = txtNombre.getText();
            if (nombre == null || nombre.isEmpty())
            	sbErrores.append("  - Nombre vacio\n");
		
            String descripcion = txtDescripcion.getText();
            if (descripcion == null || descripcion.isEmpty())
            	sbErrores.append("  - Descripción vacia\n");
		
            if (cbZona.getSelectedItem().equals("Seleccionar"))
            	sbErrores.append("  - Zona sin seleccionar\n");
		
            if (cbGrupo.getSelectedItem().equals("Seleccionar"))
            	sbErrores.append("- Grupo sin seleccionar");
		
            if (!sbErrores.isEmpty()) {
            	JOptionPane.showMessageDialog(this, "Formulario incorrecto:\n" + sbErrores.toString());
            	return;
            }
		
            Musculo musculo = new Musculo(null, nombre, descripcion, (String) cbZona.getSelectedItem(), (String) cbGrupo.getSelectedItem());
            int filaSeleccionada = tblMusculos.getSelectedRow();
		
            if (filaSeleccionada > 0 && esMusculoSeleccionado) {
            	// UPDATE
            	Integer idMusculo = (Integer) tableModel.getValueAt(tblMusculos.getSelectedRow(), 0);      			
            	if (idMusculo == null) {
            		JOptionPane.showMessageDialog(this, "Músculo seleccionado no válido");
            		return;
            	}
			
            	musculo.setIdMusculo(idMusculo);
            	MusculoService.update(idMusculo, musculo);
                JOptionPane.showMessageDialog(this, "Músculo actualizado correctamente");
            } else {
            	// INSERT
            	MusculoService.add(musculo);
                JOptionPane.showMessageDialog(this, "Músculo guardado correctamente");
            }
		
            reiniciarCampos();
            recargarMusculos();            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido algún error desconocido al intentar guardar el formulario");
            System.err.println("Error al guardar el formulario: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarMusculoActionPerformed

    private void tblMusculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMusculosMouseClicked
        Integer idMusculo = (Integer) tableModel.getValueAt(tblMusculos.getSelectedRow(), 0);            
        if (evt.getClickCount() == 1 && idMusculo == null) {
            txtaDetalles.setText("");
            esMusculoSeleccionado = false;
            return;
        }
        
        if (evt.getClickCount() == 2 && idMusculo == null) {
            reiniciarCampos();
            esMusculoSeleccionado = false;
            return;
        }
        
        Musculo musculo = MusculoService.get(idMusculo);        
        if (evt.getClickCount() == 1) {
            StringBuilder sb = new StringBuilder();
            sb.append("<> ").append(musculo.getNombre()).append("\n");
            sb.append("  - Descripción: ").append(musculo.getDescripcion()).append("\n");
            sb.append("  - Zona: ").append(musculo.getZona()).append("\n");
            sb.append("  - Grupo: ").append(musculo.getGrupo());
            txtaDetalles.setText(sb.toString());
        }
        
        if (evt.getClickCount() == 2) {
            esMusculoSeleccionado = true;
            
            txtNombre.setText(musculo.getNombre());
            txtDescripcion.setText(musculo.getDescripcion());
            cbZona.setSelectedItem(musculo.getZona());
            cbGrupo.setSelectedItem(musculo.getGrupo());
        }
    }//GEN-LAST:event_tblMusculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException e) {
            System.err.println("Error: " + e);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioMusculos dialog = new FormularioMusculos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarMusculo;
    private javax.swing.JButton btnGuardarMusculo;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JComboBox<String> cbZona;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblZona;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JScrollPane spDetalles;
    private javax.swing.JScrollPane spTblMusculos;
    private javax.swing.JTable tblMusculos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtaDetalles;
    // End of variables declaration//GEN-END:variables
}
